[project]
name = "temp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "aiohttp>=3.12.13",
    "aiortc>=1.13.0",
    "asyncio>=3.4.3",
    "requests>=2.32.4",
    "websockets>=15.0.1",
]
